chsilo1 = int(input("введите число1"))
chislo2 = int(input("введите число2"))
text = input("введите слово")
drobnoe = float(input("введите дробное число"))
print(text, chsilo1, chislo2)
print(drobnoe)
