import math
tabletki = float(input('введите количество таблеток'))
brak_tabletok = float(input('введите брак таблеток'))
gotowaya = int(input('введите количество готовой продукции'))
weight = float(input('введите средний вес'))
pachka = float(input('введите количество таблеток в пачке'))
okk = int(input('введите отбор окк'))
brak_pachek = int(input('введите количество бракованных пачек'))
itogo_fas = (tabletki-brak_tabletok)
vihod_fas = (itogo_fas*100/tabletki)
ojidaem_upak = round(itogo_fas*1000/weight/pachka)
vsego_isp = (gotowaya+brak_pachek+okk)
otklonenye = ((ojidaem_upak-vsego_isp)*100/ojidaem_upak)
print(itogo_fas)
print(vihod_fas)
print(ojidaem_upak)
print(vsego_isp)
print(otklonenye)
